FROM python:3.10-slim

WORKDIR /app

COPY collector/ ./collector/
COPY collector/config.yaml ./collector/config.yaml
COPY requirements.txt ./
ENV PYTHONPATH=/app

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "collector/main.py"]