version: "3.8"

services:
  collector:
    build:
      context: .
      dockerfile: Dockerfile.collector
    container_name: data-collector
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./duckdb:/app/duckdb
    networks:
      - ainet
    restart: always

  triton-builder:
    build:
      context: .
      dockerfile: Dockerfile.triton
    container_name: triton-builder
    depends_on:
      - kafka
    networks:
      - ainet
    restart: always

  multi-agent-runner:
    build:
      context: .
      dockerfile: Dockerfile.runner
    container_name: multi-agent-runner
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./models:/models
      - ./data:/app/data
      - ./duckdb:/app/duckdb
    env_file:
      - .env
    networks:
      - ainet
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  redis:
    image: redis:7.0
    container_name: redis-ai
    ports:
      - "6380:6379"
    networks:
      - ainet
    restart: on-failure
    command: >
      redis-server --appendonly yes --auto-aof-rewrite-percentage 50 --auto-aof-rewrite-min-size 128mb
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka-broker
    networks:
      - ainet
    ports:
      - "29092:29092"
    environment:
      KAFKA_KRAFT_CLUSTER_ID: "kafka-cluster-ainet"
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,EXTERNAL://:29092,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    restart: always
    volumes:
      - kafka-data:/bitnami/kafka
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server=localhost:9092", "--list" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    networks:
      - ainet
    ports:
      - "8088:8080"
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    restart: always

  triton:
    image: nvcr.io/nvidia/tritonserver:24.03-py3
    container_name: triton-inference
    depends_on:
      - multi-agent-runner
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - ./models:/models
    command: [ "tritonserver", "--model-repository=/models", "--model-control-mode=poll", "--repository-poll-secs=30" ]
    ports:
      - "8010:8000"
      - "8011:8001"
      - "8012:8002"
    networks:
      - ainet
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/v2/health/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  llm-agent:
    build:
      context: .
      dockerfile: Dockerfile.llm_agent
    container_name: llm-agent
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_BROKER=kafka:9092
    networks:
      - ainet
    restart: always

  vllm-server:
    image: vllm/vllm-openai:latest
    container_name: vllm-server
    environment:
      - MODEL_NAME=mistralai/Mistral-7B-Instruct-v0.2
    ports:
      - "8020:8000"
    networks:
      - ainet
    volumes:
      - ./vllm_models:/root/.cache/huggingface # 모델 캐시
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    restart: always

networks:
  ainet:
    driver: bridge

volumes:
  kafka-data:
  redis-data:
