FROM python:3.10-slim

WORKDIR /app

COPY collector/ ./collector/
COPY gateway/ ./gateway/ 
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "collector/main.py"]