FROM python:3.10-slim

WORKDIR /app

# 필수 패키지 설치
COPY requirements_trainer.txt /app/
RUN pip install --no-cache-dir -r requirements_trainer.txt

# Binance Collector 코드 복사
COPY trainer /app/trainer

# collector 실행
CMD ["python", "/app/trainer/training_pattern_consumer.py"]
