FROM python:3.10-slim

WORKDIR /app

COPY requirements_collector.txt /app/
RUN pip install --no-cache-dir -r requirements_collector.txt

COPY gateway /app/gateway
COPY data_collector /app/data_collector

ENV PYTHONPATH=/app
CMD ["python", "/app/data_collector/binance_collector.py"]
