FROM nvidia/cuda:12.6.0-runtime-ubuntu20.04

WORKDIR /app
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY ai_model /app/ai_model
CMD ["python", "ai_model/serve.py"]