FROM python:3.10-slim

WORKDIR /app

# requirements 복사 및 설치
COPY requirements_gateway.txt /app/
RUN pip install --no-cache-dir -r requirements_gateway.txt

# gateway 코드 복사
COPY gateway /app/gateway

# 환경 변수 설정
ENV PYTHONPATH=/app/gateway

# FastAPI 앱 실행
CMD ["uvicorn", "gateway.main:app", "--host", "0.0.0.0", "--port", "8080"]
