volume_ae_btc:
  topic: volume_training_btcusdt
  model_path: /models/volume_ae
  input_dim: 5
  sequence_length: 100
  d_model: 64
  learning_rate: 0.001
  recon_error_threshold: 0.05

volume_ae_eth:
  topic: volume_training_ethusdt
  model_path: /models/volume_ae
  input_dim: 5
  sequence_length: 100
  d_model: 64
  learning_rate: 0.001
  recon_error_threshold: 0.05

volume_ae_sol:
  topic: volume_training_solusdt
  model_path: /models/volume_ae
  input_dim: 5
  sequence_length: 100
  d_model: 64
  learning_rate: 0.001
  recon_error_threshold: 0.05

volatility_watcher_btc:
  topic: volatility_training_btcusdt
  model_path: /models/volatility_watcher
  input_dim: 5
  sequence_length: 100
  d_model: 64
  learning_rate: 0.001
  recon_error_threshold: 0.05

volatility_watcher_eth:
  topic: volatility_training_ethusdt
  model_path: /models/volatility_watcher
  input_dim: 5
  sequence_length: 100
  d_model: 64
  learning_rate: 0.001
  recon_error_threshold: 0.05

volatility_watcher_sol:
  topic: volatility_training_solusdt
  model_path: /models/volatility_watcher
  input_dim: 5
  sequence_length: 100
  d_model: 64
  learning_rate: 0.001
  recon_error_threshold: 0.05

overheat_detector_btc:
  topic: overheat_training_btcusdt
  model_path: /models/overheat_detector
  input_dim: 5
  sequence_length: 100
  d_model: 64
  learning_rate: 0.001
  recon_error_threshold: 0.05

overheat_detector_eth:
  topic: overheat_training_ethusdt
  model_path: /models/overheat_detector
  input_dim: 5
  sequence_length: 100
  d_model: 64
  learning_rate: 0.001
  recon_error_threshold: 0.05

overheat_detector_sol:
  topic: overheat_training_solusdt
  model_path: /models/overheat_detector
  input_dim: 5
  sequence_length: 100
  d_model: 64
  learning_rate: 0.001
  recon_error_threshold: 0.05

pattern_ae_btc:
  topic: pattern_training_btcusdt
  model_path: /models/pattern_ae
  input_dim: 5
  sequence_length: 100
  d_model: 64
  learning_rate: 0.001
  recon_error_threshold: 0.05

pattern_ae_eth:
  topic: pattern_training_ethusdt
  model_path: /models/pattern_ae
  input_dim: 5
  sequence_length: 100
  d_model: 64
  learning_rate: 0.001
  recon_error_threshold: 0.05

pattern_ae_sol:
  topic: pattern_training_solusdt
  model_path: /models/pattern_ae
  input_dim: 5
  sequence_length: 100
  d_model: 64
  learning_rate: 0.001
  recon_error_threshold: 0.05

noise_filter_btc:
  topic: noise_training_btcusdt
  model_path: /models/noise_filter
  input_dim: 5
  sequence_length: 100
  hidden_size: 64
  learning_rate: 0.001

noise_filter_eth:
  topic: noise_training_ethusdt
  model_path: /models/noise_filter
  input_dim: 5
  sequence_length: 100
  hidden_size: 64
  learning_rate: 0.001

noise_filter_sol:
  topic: noise_training_solusdt
  model_path: /models/noise_filter
  input_dim: 5
  sequence_length: 100
  hidden_size: 64
  learning_rate: 0.001

liquidity_checker_btc:
  topic: liquidity_training_btcusdt
  model_path: /models/liquidity_checker
  input_dim: 5
  sequence_length: 100
  d_model: 64
  learning_rate: 0.001

liquidity_checker_eth:
  topic: liquidity_training_ethusdt
  model_path: /models/liquidity_checker
  input_dim: 5
  sequence_length: 100
  d_model: 64
  learning_rate: 0.001

liquidity_checker_sol:
  topic: liquidity_training_solusdt
  model_path: /models/liquidity_checker
  input_dim: 5
  sequence_length: 100
  d_model: 64
  learning_rate: 0.001

risk_scorer_btc:
  topic: risk_training_btcusdt
  model_path: /models/risk_scorer
  input_dim: 5
  sequence_length: 100
  hidden_size: 64
  num_classes: 2
  learning_rate: 0.001

risk_scorer_eth:
  topic: risk_training_ethusdt
  model_path: /models/risk_scorer
  input_dim: 5
  sequence_length: 100
  hidden_size: 64
  num_classes: 2
  learning_rate: 0.001

risk_scorer_sol:
  topic: risk_training_solusdt
  model_path: /models/risk_scorer
  input_dim: 5
  sequence_length: 100
  hidden_size: 64
  num_classes: 2
  learning_rate: 0.001

trend_segmenter_btc:
  topic: trend_training_btcusdt
  model_path: /models/trend_segmenter
  input_dim: 5
  sequence_length: 100
  d_model: 64
  num_classes: 3
  learning_rate: 0.001

trend_segmenter_eth:
  topic: trend_training_ethusdt
  model_path: /models/trend_segmenter
  input_dim: 5
  sequence_length: 100
  d_model: 64
  num_classes: 3
  learning_rate: 0.001

trend_segmenter_sol:
  topic: trend_training_solusdt
  model_path: /models/trend_segmenter
  input_dim: 5
  sequence_length: 100
  d_model: 64
  num_classes: 3
  learning_rate: 0.001
