topics:
  liquidity_training_btcusdt: liquidity_checker
  trend_training_btcusdt: trend_segmenter
  noise_training_btcusdt: noise_filter
  risk_training_btcusdt: risk_scorer
  pattern_training_btcusdt: pattern_ae
  volume_training_btcusdt: volume_ae
  macro_training___tnx_1d: macro_filter_tnx
  macro_training___gspc_1d: macro_filter_gspc
  macro_training_gc_f_1d: macro_filter_gold
  overheat_training_btcusdt: overheat_detector
  volatility_training_btcusdt: volatility_watcher

routing:
  liquidity_training_btcusdt: risk_training_btcusdt
  trend_training_btcusdt: risk_training_btcusdt
  noise_training_btcusdt: risk_training_btcusdt
  macro_training___tnx_1d: risk_training_btcusdt
  macro_training___gspc_1d: risk_training_btcusdt
  macro_training_gc_f_1d: risk_training_btcusdt
  # 위 모든 결과를 모아 전송
  risk_training_btcusdt: ai_intermediate_outputs
