binance_symbols:
  - BTCUSDT
  - ETHUSDT
  - SOLUSDT

macro_symbols:
  - "^GSPC" # S&P500
  - "^TNX" # 10Y US Treasury
  - "GC=F" # Gold Futures
  - "CL=F" # Crude Oil Futures

intervals:
  - 1m
  - 5m
  - 1h
  - 1d

kafka_broker: "kafka:9092"
