topic: volatility_training_btcusdt_1m
model_path: /models/volatility_watcher/1/model.onnx
batch_size: 32
learning_rate: 0.001
input_dim: 5
sequence_length: 100
d_model: 64
recon_error_threshold: 0.05
